apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ruralcart
  labels:
    app: ruralcart
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ruralcart
  template:
    metadata:
      labels:
        app: ruralcart
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ruralcart
          image: ghcr.io/jithinrmklu/ruralcart:27f9590
          ports:
            - containerPort: 80
  strategy:
    blueGreen:
      activeService: ruralcart-stable
      previewService: ruralcart-preview
      autoPromotionEnabled: false  # Manual promotion required
